# syntax=docker/dockerfile:1

FROM mcr.microsoft.com/dotnet/sdk:9.0-alpine AS build

COPY ./shared/McpSamples.Shared /source/shared/McpSamples.Shared
COPY ./awesome-copilot/src/McpSamples.AwesomeCopilot.HybridApp /source/awesome-copilot/src/McpSamples.AwesomeCopilot.HybridApp

WORKDIR /source/awesome-copilot/src/McpSamples.AwesomeCopilot.HybridApp

RUN dotnet publish -c Release -o /app --self-contained false

FROM mcr.microsoft.com/dotnet/aspnet:9.0-alpine AS final

WORKDIR /app

COPY --from=build /app .

USER $APP_UID

ENTRYPOINT ["dotnet", "McpSamples.AwesomeCopilot.HybridApp.dll"]
