# syntax=docker/dockerfile:1

FROM mcr.microsoft.com/dotnet/sdk:9.0-alpine AS build

COPY ./src/McpAwesomeCopilot.Common /source/McpAwesomeCopilot.Common
COPY ./src/McpAwesomeCopilot.ContainerApp /source/McpAwesomeCopilot.ContainerApp

WORKDIR /source/McpAwesomeCopilot.ContainerApp

RUN dotnet publish -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:9.0-alpine AS final

WORKDIR /app

COPY --from=build /app .

USER $APP_UID

ENTRYPOINT ["dotnet", "McpAwesomeCopilot.ContainerApp.dll"]
