# syntax=docker/dockerfile:1

FROM mcr.microsoft.com/dotnet/sdk:9.0-alpine AS build

COPY ./src/McpMarkdownToHtml.Common /source/McpMarkdownToHtml.Common
COPY ./src/McpMarkdownToHtml.ContainerApp /source/McpMarkdownToHtml.ContainerApp

WORKDIR /source/McpMarkdownToHtml.ContainerApp

RUN dotnet publish -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:9.0-alpine AS final

WORKDIR /app

COPY --from=build /app .

USER $APP_UID

ENTRYPOINT ["dotnet", "McpMarkdownToHtml.ContainerApp.dll"]
